---
title: "Best Models"
author: "Samantha Su"
date: "2025-06-04"
output: html_document
---

```{r, message = F, warning = F}
# Load in the libraries
library(tidyverse)
library(sdmTMB)
library(ggplot2)
library(readr)
library(ggcorrplot)
library(Metrics)
library(naniar)
library(tibble)
library(rsample)
library(caret)
library(purrr)
library(tune)
library(patchwork)

# Read in the data
cal_data <- read.csv("../../data/Merged_CalCOFI/merged_std_data_05_13_25.csv")
```

## Cleaning the Data

```{r}
# Removing the first two columns
cal_data <- cal_data[, -c(1,2)]

# Changing dataset to only have present response data
cal_data <- cal_data %>% 
  filter(!is.na(b_scaled))
```

## Splitting the Data

```{r}
# Split data into training and testing sets with most recent year as our testing set
set.seed(123)
last_year <- max(cal_data$year)
train_data <- cal_data %>% filter(year != last_year)
test_data <- cal_data %>% filter(year == last_year)
```

## A Call

```{r, eval = FALSE}
# Create mesh using training data
mesh_train <- make_mesh(train_data,
                        xy_cols = c("X", "Y"),
                        cutoff = 15)

# Fit spatiotemporal model
fit_A <- sdmTMB(
  a_scaled ~ temperature_depth_55 + lat + lon , 
  data = train_data, 
  mesh = mesh_train,
  time = "season",
  family = delta_gamma(link1 = "logit", link2 = "log"), 
  spatial = "on", 
  spatiotemporal = "rw",
  extra_time = unique(test_data$season)
)

# Predictions on training and test data
training_pred <- predict(fit_A, newdata = train_data, type = "response")
training_pred$observed <- train_data$a_scaled

test_pred <- predict(fit_A, newdata = test_data, type = "response")
test_pred$observed <- test_data$a_scaled

# Compute RMSE
rmse_train <- rmse(training_pred$observed, training_pred$est)
rmse_test <- rmse(test_pred$observed, test_pred$est)

# Compute Range
range_train <- range(train_data$a_scaled)
range_test <- range(test_data$a_scaled)

# Compute Standard Deviation
sd_train <- sd(train_data$a_scaled, na.rm = TRUE)
sd_test <- sd(test_data$a_scaled, na.rm = TRUE)

# Assemble the table
summary_table_A <- data.frame(
  Dataset = c("Training", "Test"),
  RMSE = c(rmse_train, rmse_test),
  Range_Min = c(range_train[1], range_test[1]),
  Range_Max = c(range_train[2], range_test[2]),
  Std_Dev = c(sd_train, sd_test)
)

print(summary_table_A)
```


## B Call

```{r, eval = FALSE}
# Create mesh using training data
mesh_train <- make_mesh(train_data,
                        xy_cols = c("X", "Y"),
                        cutoff = 10)

# Fit spatiotemporal model
fit_spatiotemporal <- sdmTMB(
  b_scaled ~ 1, 
  data = train_data, 
  mesh = mesh_train,
  time = "season",
  family = delta_gamma(link1 = "logit", link2 = "log"), 
  spatial = "off", 
  spatiotemporal = "rw",
  extra_time = unique(test_data$season)
)

# Predictions on training and test data
training_pred <- predict(fit_spatiotemporal, newdata = train_data, type = "response")
training_pred$observed <- train_data$b_scaled

test_pred <- predict(fit_spatiotemporal, newdata = test_data, type = "response")
test_pred$observed <- test_data$b_scaled

# Plotting the predictions
pA_train <- ggplot(training_pred, aes(x = observed, y = est)) + 
  geom_point() + 
  ggtitle("Train") + 
  geom_abline(intercept = 0, slope = 1, col = "red")

pA_test <- ggplot(test_pred, aes(x = observed, y = est)) + 
  geom_point() + 
  ggtitle("Test") + 
  geom_abline(intercept = 0, slope = 1, col = "red")

gridExtra::grid.arrange(pA_train, pA_test)

# Compute RMSE
rmse_train <- rmse(training_pred$observed, training_pred$est)
rmse_test <- rmse(test_pred$observed, test_pred$est)

# Compute Range
range_train <- range(train_data$b_scaled)
range_test <- range(test_data$b_scaled)

# Compute Standard Deviation
sd_train <- sd(train_data$b_scaled, na.rm = TRUE)
sd_test <- sd(test_data$b_scaled, na.rm = TRUE)

# Assemble the table
summary_table4 <- data.frame(
  Dataset = c("Training", "Test"),
  RMSE = c(rmse_train, rmse_test),
  Range_Min = c(range_train[1], range_test[1]),
  Range_Max = c(range_train[2], range_test[2]),
  Std_Dev = c(sd_train, sd_test)
)

summary_table4
```


## D Call

```{r}
# Create mesh using training data
mesh_train <- make_mesh(train_data,
                        xy_cols = c("X", "Y"),
                        cutoff = 10)

# Fit spatiotemporal model
fit_spatiotemporal <- sdmTMB(
  d_scaled ~ lat + lon + temperature_depth_55_std + salinity_depth_55_std + magnitude_depth_55_std + theta_depth_55_std,  
  data = train_data, 
  mesh = mesh_train,
  time = "season",
  family = delta_gamma(link1 = "logit", link2 = "log"), 
  spatial = "on", 
  spatiotemporal = "iid",
  extra_time = unique(test_data$season)
)

# Extract coefficients and sanity check
#tidy(fit_spatiotemporal, conf.int = TRUE)
sanity(fit_spatiotemporal)

# Predictions on training and test data
training_pred <- predict(fit_spatiotemporal, newdata = train_data, type = "response")
training_pred$observed <- train_data$d_scaled

test_pred <- predict(fit_spatiotemporal, newdata = test_data, type = "response")
test_pred$observed <- test_data$d_scaled

# Plotting the predictions
p0 <- ggplot(training_pred, aes(x = observed, y = est)) + 
  geom_point() + 
  ggtitle("Train") + 
  geom_abline(intercept = 0, slope = 1, col = "red")

p1 <- ggplot(test_pred, aes(x = observed, y = est)) + 
  geom_point() + 
  ggtitle("Test") + 
  geom_abline(intercept = 0, slope = 1, col = "red")

gridExtra::grid.arrange(p0, p1)

# Compute RMSE
rmse_train <- rmse(training_pred$observed, training_pred$est)
rmse_test <- rmse(test_pred$observed, test_pred$est)

# Compute Range
range_train <- range(train_data$d_scaled, na.rm = TRUE)
range_test <- range(test_data$d_scaled, na.rm = TRUE)

# Compute Standard Deviation
sd_train <- sd(train_data$d_scaled, na.rm = TRUE)
sd_test <- sd(test_data$d_scaled, na.rm = TRUE)

# Assemble the table
summary_table <- data.frame(
  Dataset = c("Training", "Test"),
  RMSE = c(rmse_train, rmse_test),
  Range_Min = c(range_train[1], range_test[1]),
  Range_Max = c(range_train[2], range_test[2]),
  Std_Dev = c(sd_train, sd_test)
)

# Print the summary table
print(summary_table)
```

## 20Hz Call

```{r}
mesh_train <- make_mesh(train_data,
                        xy_cols = c("X", "Y"),
                        cutoff = 5)

# Fit spatiotemporal model
fit_spatiotemporal <- sdmTMB(
  x20hz_scaled ~ temperature_depth_105_std + temperature_depth_55_std + temperature_depth_280_std + salinity_depth_55_std + salinity_depth_105_std + magnitude_depth_55_std + magnitude_depth_105_std + theta_depth_55_std + theta_depth_105_std,  
  data = train_data, 
  mesh = mesh_train,
  time = "season",
  family = delta_gamma(link1 = "logit", link2 = "log"),
  spatial = "on", 
  spatiotemporal = "ar1",
  extra_time = unique(test_data$season)
)

# Predictions on training and test data
training_pred <- predict(fit_spatiotemporal, newdata = train_data, type = "response")
training_pred$observed <- train_data$x40hz_scaled

test_pred <- predict(fit_spatiotemporal, newdata = test_data, type = "response")
test_pred$observed <- test_data$x40hz_scaled

# Plotting the predictions
p0 <- ggplot(training_pred, aes(x = observed, y = est)) + 
  geom_point() + 
  ggtitle("Train") + 
  geom_abline(intercept = 0, slope = 1, col = "red")

p1 <- ggplot(test_pred, aes(x = observed, y = est)) + 
  geom_point() + 
  ggtitle("Test") + 
  geom_abline(intercept = 0, slope = 1, col = "red")

gridExtra::grid.arrange(p0, p1)

# Compute RMSE
rmse_train <- rmse(training_pred$observed, training_pred$est)
rmse_test <- rmse(test_pred$observed, test_pred$est)

# Compute Range
range_train <- range(train_data$x40hz_scaled, na.rm = TRUE)
range_test <- range(test_data$x40hz_scaled, na.rm = TRUE)

# Compute Standard Deviation
sd_train <- sd(train_data$x40hz_scaled, na.rm = TRUE)
sd_test <- sd(test_data$x40hz_scaled, na.rm = TRUE)

# Assemble the table
summary_table <- data.frame(
  Dataset = c("Training", "Test"),
  RMSE = c(rmse_train, rmse_test),
  Range_Min = c(range_train[1], range_test[1]),
  Range_Max = c(range_train[2], range_test[2]),
  Std_Dev = c(sd_train, sd_test)
)

# Print the summary table
print(summary_table)
```


## 40Hz Call

```{r}
mesh_train <- make_mesh(
  train_data, c("X", "Y"),
  cutoff = 35
)

fit_spatiotemporal <- sdmTMB(
  x40hz_scaled ~ temperature_depth_55_std + salinity_depth_55_std + magnitude_depth_55_std,
  mesh = mesh_train,
  data = train_data, 
  time = "season",
  family = delta_gamma(link1 = "cloglog", link2 = "log"),
  spatial = "on", 
  spatiotemporal = "iid",
  extra_time = unique(test_data$season)
)

# Extract coefficients and sanity check
# tidy(fit_spatiotemporal, conf.int = TRUE)

# Predictions on training and test data
training_pred <- predict(fit_spatiotemporal, newdata = train_data, type = "response")
training_pred$observed <- train_data$x40hz_scaled

test_pred <- predict(fit_spatiotemporal, newdata = test_data, type = "response")
test_pred$observed <- test_data$x40hz_scaled

# Plotting the predictions
p0 <- ggplot(training_pred, aes(x = observed, y = est)) + 
  geom_point() + 
  ggtitle("Train") + 
  geom_abline(intercept = 0, slope = 1, col = "red")

p1 <- ggplot(test_pred, aes(x = observed, y = est)) + 
  geom_point() + 
  ggtitle("Test") + 
  geom_abline(intercept = 0, slope = 1, col = "red")

gridExtra::grid.arrange(p0, p1)

# Compute RMSE
rmse_train <- rmse(training_pred$observed, training_pred$est)
rmse_test <- rmse(test_pred$observed, test_pred$est)

# Compute Range
range_train <- range(train_data$x40hz_scaled, na.rm = TRUE)
range_test <- range(test_data$x40hz_scaled, na.rm = TRUE)

# Compute Standard Deviation
sd_train <- sd(train_data$x40hz_scaled, na.rm = TRUE)
sd_test <- sd(test_data$x40hz_scaled, na.rm = TRUE)

# Assemble the table
summary_table <- data.frame(
  Dataset = c("Training", "Test"),
  RMSE = c(rmse_train, rmse_test),
  Range_Min = c(range_train[1], range_test[1]),
  Range_Max = c(range_train[2], range_test[2]),
  Std_Dev = c(sd_train, sd_test)
)

# Print the summary table
print(summary_table)
```

```{r}
summary(fit_spatiotemporal)
```
